export const VOD_LIST = [
  "🎬 BLOCKBUSTER CINEMA",
  "🎥 NETFLIX ORIGINALS",
  "🍿 BINGE-WORTHY SERIES",
  "🏆 LIVE SPORTS VAULT",
  "⛩️ ANIME UNIVERSE",
  "🚀 KIDS GALAXY",
  "BROADWAY/MUSICAL",
  "Netflix Premium 4K + HDR",
  "NETFLIX 4K (ULTRA HD) + HDR Kids",
  "Disney Kids",
  "HBO",
  "HULU",
  "UFC",
  "HBO MAX",
  "National Geography",
  "Netflix ASIA",
  "Pixar",
  "Disney +",
  "Marvel",
  "1 - TOP 500 IMDB",
  "2 - NETFLIX 4K",
  "3 - NETFLIX VOD",
  "4 - APPLE+",
  "5 - DISNEY+",
  "6 - ENGLISH 4K",
  "7 - ENGLISH MOVIES",
  "8 - ENGLISH SERIES",
  "9 - NETHERLANDS 4K",
  "10 - NETHERLANDS VOD",
  "11 - FRANCE 4K",
  "12 - FRANCE MOVIES",
  "13 - FRANCE SERIES",
  "14 - QUEBEC",
  "15 - SPAIN VOD",
  "16 - PORTUGAL VOD",
  "17 - BRASIL",
  "18 - GERMANY MOVIES",
  "19 - GERMANY SERIES",
  "20 - POLISH VOD",
  "21 - ITALY 4K",
  "22 - ITALIAN VOD",
  "23 - SCANDINAVIA MULTI-SUB",
  "24 - SWEDEN VOD",
  "25 - SWEDEN VOD PREMIUM",
  "26 - SWEDEN SERIES PREMIUM",
  "27 - SWEDEN MUSIC PREMIUM",
  "28 - DENMARK VOD",
  "29 - NORWAY VOD",
  "30 - FINLAND VOD",
  "31 - GREECE VOD",
  "32 - ARABIC VOD",
  "33 - TURKISH VOD",
  "34 - INDIA VOD",
  "35 - PAKISTAN",
  "36 - IRAN VOD",
  "37 - ISRAEL",
  "38 - ROMANIA",
  "39 - BULGARIA",
  "40 - Hungary",
  "41 - ALBANIA",
  "42 - EXYU VOD",
  "43 - RUSSIA VOD",
  "44 - MALTA",
  "45 - AFRICA",
  "46 - SOMALIA",
  "47 - PHILIPPINES",
  "48 - CHINESE",
  "49 - JAPANESE SUB",
  "50 - SPORT VOD",
  "51 - ADULT VOD"
];

export const PACKAGE_LIST = [
  "1 - BEETV Arabic",
  "2 - Arabic",
  "3 - Arabic (Islamic only)",
  "4 - 4K UHD 3840P",
  "5 - Ultimate - Usa",
  "6 - USA 24/7",
  "7 - Ultimate - Canada",
  "8 - 24/7 English",
  "9 - Sports Live",
  "10 - Spain",
  "11 - Germany",
  "12 - Swiss/Austria",
  "13 - Portugal",
  "14 - Italy",
  "15 - Netherlands",
  "16 - Belgium",
  "17 - United Kingdom",
  "18 - Poland",
  "19 - Greece Premium",
  "20 - Greece FTA",
  "21 - Armenia",
  "22 - Malta",
  "23 - SCA - Sweden Ultimate",
  "24 - SCA - Denmark Ultimate",
  "25 - SCA - Norway Ultimate",
  "26 - SCA - Finland Ultimate",
  "27 - Albania",
  "28 - Slovenia",
  "29 - Exyu",
  "30 - Lithuania",
  "31 - Latvia",
  "32 - Estonia",
  "33 - Hungary",
  "34 - Czech",
  "35 - Romania",
  "36 - Bulgaria",
  "37 - Russia",
  "38 - Ukraine",
  "39 - Georgia/Kazach",
  "40 - Australia",
  "41 - New Zealand",
  "42 - Brasil",
  "43 - Latino",
  "44 - Carribean",
  "45 - Sorted - France",
  "46 - India",
  "47 - India Punjab",
  "48 - Turkey",
  "49 - Iran",
  "50 - Afghanistan",
  "51 - Pakistan",
  "52 - Azerbaycan",
  "53 - Uzbekistan",
  "54 - Tajikistan",
  "55 - Kurdistan",
  "56 - Formule 1 + MotoGP",
  "57 - Viaplay PPV",
  "58 - Israel",
  "59 - China/HK",
  "60 - Korea",
  "61 - Indonesia",
  "62 - Myanmar",
  "63 - Thailand",
  "64 - Singapore",
  "65 - Taiwan",
  "66 - Vietnam",
  "67 - Malaysia",
  "68 - Japan",
  "69 - Philippines",
  "70 - Suriname",
  "71 - Africa DSTV",
  "72 - Africa FTA",
  "73 - World Cricket",
  "74 - Horse Racing",
  "75 - Music Concerts",
  "76 - Adults",
  "77 - SCA - Iceland"
];
